### ISSUE TITLE
Embeded installation - cannot open some links (Privileges, Subjects etc.)

### ISSUE THREAD

**Issue by mariusz-zawadzki** [OpenIdentityPlatform/OpenAM#76] opened 2018-08-20 11:38 UTC
Hi. 

I've managed to install and run openam on my local tomcat. I'm trying to do a POC of available SSO solutions.

The problem I'm having is that for some items in realm admin dasboard ( ?service=adminconsoleservice ) links lead to:
http://mydomain.com:8080/openam/XUI/?service=adminconsoleservice#

Which opens a login screen and not the expected page.

**To Reproduce**
New tomcat (apache-tomcat-8.5.32 )installation, 
open am 14.1.8.war or 14.1.7.war

**Expected behavior**
All links lead to expected places, for admin user.

Affected links:
Applications (SAML 2.0, WS-Fed, OAuth 2.0, J2EE Agents, Web Agents)
Data Stores
Privileges
Subjects
STS

**Comment by maximthomas** [comment] 2018-08-24 08:18
Well, there are no XUI implementations for these links yet, they are sitll leading to legacy UI. We plan to implement this in further releases.

**Comment by mariusz-zawadzki** [comment] 2018-08-24 08:33
@maximthomas : the problem is not that they lead to old UI (because they don't). They lead to nowhere currently. For older version (13.5? I don't rember exactly) that I got from ForgeRock.org they **do open old UI**  for 14.x they don't open anything, just lead to login page.

**Comment by maximthomas** [comment] 2018-08-24 08:47
@mariusz-zawadzki, could you record har log while you click on Applications -> SAML 2.0 link, or something. Please, click preserver log, so we can track all browser redirects.

**Comment by maximthomas** [comment] 2018-09-05 07:45
Hello, @mariusz-zawadzki, do you still facing this issue? Could you provide har log, because we cant reproduce this issue?

**Comment by mariusz-zawadzki** [comment] 2018-09-08 16:19
@maximthomas 
Hi. Sorry for the delayed response. Had no chance to look into this, for now we picked another solution OAuth.
I'll try to provide you the redirection log today or tomorrow.

**Comment by mariusz-zawadzki** [comment] 2018-09-08 16:32
@maximthomas : I just tried with fresh instalation on my personal laptop and it works fine. 
So it looks like a problem on my work laptop, maybe I screwed up some settings. On monday I will check what was happening there and hopefully will be able to recreate the issue and find the root cause. (for now only thing that comes to my mind is that on my personal laptop I don't have any domains set up and just use pure 'localhost' )

So please keep this issue opened and on monday I will try to find what is happening (but most probably the issue is on host settings of my machine).

**Comment by maximthomas** [comment] 2018-09-10 06:01
@mariusz-zawadzki thanks for information! I'm closing this issue for now. If you'll find something else, let us know!)

**Closed as completed by maximthomas** 2018-09-10 06:01 UTC
